INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 4 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

MAX_HISTORY: 8 # Set the maximum message history

PRESENCES_CHANGE_DELAY: 6 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

Discord: https://discord.gg/bUNZ527f

TRIGGER:
  - chatbot
  - bot nickname
  - bot alias
  - bot name
  - Other bot alias...
# Define the triggers that the bot should always respond to when in message

PRESENCES:
  - How can I assist you?
  - Currently in {guild_count} guilds
# List of different presences to be used
